### ISSUE TITLE
Integrate bootstrap framework.

### ISSUE THREAD

**Issue by Daltyn06** [madwelljawnz/helloworld#3]
https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by madwelljawnz** [comment]
i think i did what is necessary here. guess i wont know until i start implementing functionalities of bootstrap within my index file right?

**Comment by Daltyn06** [comment]
@madwelljawnz yea you did it right you can see that the col classes work because the site is in two columns.
